#!/usr/bin/env bash

#docker pull strauzr:5000/strauz/caudal:0.7.4.1

if [ $# -ne 1 ] ; then
  echo "Usage: ./bin/create-caudal VERSION"
  echo
  echo "  e.g. ./bin/create-caudal 0.1.0"
  echo
  exit 0
fi

export CAUDAL_VERSION=$1

docker service create --name caudal \
                      --replicas 1 \
                      --limit-cpu 50 --limit-memory 256m \
                      --restart-condition on-failure \
                      --publish 12201:12201/udp
                      --user=strauz:strauz \
                      strauzr:5000/strauz/caudal:$CAUDAL_VERSION